### ISSUE TITLE
subscription api wrong mandatory fields

### ISSUE THREAD

**Issue by philipp1992** [killbill/killbill-client-js#17]
in the interface definition of Subscription, the following attributes are mandatory in the sense of the typescript interface definition

- planname
- productlist
- productname
- billingPeriod

according to the kill bill documentation, those fields are not mandatory. also it seems that productname and planname are mutually exclusive, because I get the following error from KB Api when creating a subscription.

SubscriptionJson productName should not be set when planName is specified'

**Comment by rajansharma3097** [comment]
@philipp1992 Are you unable to solve this issue? I'm also facing the same issue.

can you please help me if you were able to solve this?

**Comment by philipp1992** [comment]
No I ditched kill Bill due to the lack of support and modern features. Sorry

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
