### ISSUE TITLE
 In progress, help welcome!???????

### ISSUE THREAD

**Issue by austinvernsonger** [killbill/killbill-client-js#4]
Do you still need help?

>  In progress, help welcome!

**Comment by pierre** [comment]
Help is always welcome! 😸 

The [Ruby](https://github.com/killbill/killbill-client-ruby) and [Java](https://github.com/killbill/killbill-client-java) clients are the two libraries we officially maintain, and we principally rely on the community to keep other flavors up-to-date ([JavaScript](https://github.com/killbill/killbill-client-js/), [Python](https://github.com/killbill/killbill-client-python), [Go](https://github.com/killbill/kbcli), etc.)

Feel free to reach-out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) if you have further questions.
