### ISSUE TITLE
Proposal of refactor

### ISSUE THREAD

**Issue by otaviosoares** [killbill/killbill-client-js#9]
With the current implementation it's not possible to override the settings.

I'd like to propose a refactor to use functions instead of objects.

For example:
in node:
```
var Killbill = require('killbill')

var killbill = new Killbill(settings);

killbill.Account.create()
```

in browser:
```
var killbill = new Killbill(settings); // or K() to maintain the current global name

killbill.Account.create()
```

What's your opinion?

**Comment by pierre** [comment]
What is the issue exactly? Can't you simply access `K.settings`?

![image](https://cloud.githubusercontent.com/assets/51940/21022622/2c010e60-bd32-11e6-8503-90691f8eae45.png)

**Comment by otaviosoares** [comment]
You're right.

Thanks
